# Generated by Django 4.1.7 on 2023-12-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0002_studentdetails_city_studentdetails_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentdetails",
            old_name="emergency_contact_contact",
            new_name="emergency_contact_number",
        ),
        migrations.RemoveField(
            model_name="studentdetails", name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="studentdetails", name="emergency_contact_relationship",
        ),
    ]
