# Generated by Django 4.1.7 on 2023-12-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0004_basicinfo_studentdetails_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentdetails", name="emergency_contact_number",
        ),
    ]
