# Generated by Django 4.1.7 on 2023-12-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0005_remove_studentdetails_emergency_contact_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="media/profile"
            ),
        ),
    ]
