# Generated by Django 4.1.7 on 2023-12-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0007_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="announce_to",
            field=models.IntegerField(default=0),
        ),
    ]
