# Generated by Django 4.1.7 on 2023-12-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0011_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message", name="receiverid", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="message", name="senderid", field=models.IntegerField(),
        ),
    ]
