# Generated by Django 4.1.7 on 2023-12-24 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schoolapp", "0014_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestMarks",
            fields=[
                (
                    "basicinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schoolapp.basicinfo",
                    ),
                ),
                ("test_id", models.IntegerField()),
                ("kannada", models.FloatField()),
                ("english", models.FloatField()),
                ("hindi", models.FloatField()),
                ("science", models.FloatField()),
                ("maths", models.FloatField()),
                ("social", models.FloatField()),
                ("total_marks", models.FloatField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schoolapp.test"
                    ),
                ),
            ],
            bases=("schoolapp.basicinfo",),
        ),
    ]
