# Generated by Django 4.1.7 on 2023-12-24 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0018_remove_testmarks_scored_marks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmarks",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="schoolapp.studentdetails",
            ),
        ),
    ]
