# Generated by Django 4.1.7 on 2023-12-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0020_testmarks_is_pass"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmarks",
            name="total_marks",
            field=models.IntegerField(default=0),
        ),
    ]
