# Generated by Django 4.1.7 on 2023-12-24 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0021_testmarks_total_marks"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 24, 21, 7, 28, 775444)
            ),
        ),
    ]
