# Generated by Django 4.1.7 on 2023-12-24 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0022_test_start_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="test",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 25, 0, 10, 15, 841166)
            ),
        ),
    ]
