# Generated by Django 4.1.7 on 2023-12-25 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0023_test_is_ready_alter_test_start_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 25, 12, 39, 55, 835476)
            ),
        ),
        migrations.AlterField(
            model_name="testmarks",
            name="english",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="testmarks", name="hindi", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="testmarks",
            name="kannada",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="testmarks", name="maths", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="testmarks",
            name="science",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="testmarks", name="social", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="testmarks",
            name="total_scored_marks",
            field=models.IntegerField(default=0),
        ),
    ]
