# Generated by Django 4.1.7 on 2023-12-25 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0024_alter_test_start_at_alter_testmarks_english_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmarks",
            name="grade",
            field=models.CharField(default="F", max_length=50),
        ),
        migrations.AlterField(
            model_name="test",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 25, 22, 43, 29, 458253)
            ),
        ),
    ]
