# Generated by Django 4.1.7 on 2023-12-26 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0025_testmarks_grade_alter_test_start_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuery",
            fields=[
                (
                    "basicinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schoolapp.basicinfo",
                    ),
                ),
                ("username", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=150)),
                ("description", models.TextField()),
            ],
            bases=("schoolapp.basicinfo",),
        ),
        migrations.AlterField(
            model_name="test",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 26, 19, 44, 18, 341266)
            ),
        ),
    ]
