# Generated by Django 4.1.7 on 2023-12-27 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0026_userquery_alter_test_start_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquery",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="test",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 27, 22, 34, 53, 451151)
            ),
        ),
    ]
